### ISSUE TITLE
Show list of installed services 

### ISSUE THREAD

**Issue by ansible42** [ni/NI-SystemLink-Migration#128]
Enhancement::  A command which shows the user which services are installed on the system, or at least which ones are reported by the tool.  Useful for debugging.

**Comment by Christian-Nunnally** [comment]
This is a good suggestion. I created a quick PR that adds this flag. I probably will need to write a few tests for it though: https://github.com/ni/NI-SystemLink-Migration/pull/131

**Comment by Christian-Nunnally** [comment]
Can now accomplish this by running `nislmigrate list` https://github.com/ni/NI-SystemLink-Migration/pull/131
