### ISSUE TITLE
Cryptography package missing 

### ISSUE THREAD

**Issue by ansible42** [ni/NI-SystemLink-Migration#129]
![image](https://user-images.githubusercontent.com/5238787/140959623-34380265-040f-4370-ae8b-9e72aa0b56b5.png)

Looks like the cryptography package is not marked as a dependency.

**Comment by Christian-Nunnally** [comment]
Here is a PR that fixes this issue: https://github.com/ni/NI-SystemLink-Migration/pull/130

Apologies for not including that package in the non development dependencies. I'll create another release when this PR goes in. Meanwhile you can run `pip install cryptography` as a work around.

**Comment by Christian-Nunnally** [comment]
Should be fixed in: https://github.com/ni/NI-SystemLink-Migration/releases/tag/0.0.32
