### ISSUE TITLE
nislmitrate.utilities.permission_checker issue finding method. 

### ISSUE THREAD

**Issue by ansible42** [ni/NI-SystemLink-Migration#132]
![image](https://user-images.githubusercontent.com/5238787/141339331-b34f3da1-d315-4a43-bde5-98ebe31b7a97.png)
Dependency issue using 0.0.33

**Comment by Christian-Nunnally** [comment]
Oh man... fix pending: https://github.com/ni/NI-SystemLink-Migration/pull/133

**Comment by Christian-Nunnally** [comment]
Created a new (non broken) release: https://github.com/ni/NI-SystemLink-Migration/releases/tag/0.0.34
