### ISSUE TITLE
List command not showing all installed services 

### ISSUE THREAD

**Issue by ansible42** [ni/NI-SystemLink-Migration#134]
![image](https://user-images.githubusercontent.com/5238787/141345915-dd195727-d48c-4e3f-adcf-8b0fd7735b83.png)

List command is not showing all services that I know are installed. The package repo sticks out.

**Comment by Christian-Nunnally** [comment]
@ansible42 What version of SystemLink do you have installed? and have you done any in place upgrades to this installation from other versions of SystemLink?

The tool thinking the package repo isn't installed is based on `%programdata%/National Instruments/Skyline/Config/PackageRepository.json` file not existing, which might be the case for older versions of SystemLink.

**Comment by ansible42** [comment]
```%programdata%/National Instruments/Skyline/Config/PackageRepository.json``` is not there.  
![image](https://user-images.githubusercontent.com/5238787/141349057-57b0c31d-13da-494d-a43d-4b3c3e45ff67.png)

I am currently running 2020r2 but this system has been upgraded several times, not sure what the original install was; 2019 maybe.

**Comment by Christian-Nunnally** [comment]
I believe the PackageRepository configuration used to be called `Repository.json`, which you do have. 

The officially tested versions of SystemLink this tool was tested on are all 2021+ so as it stands that's not going to be officially supported :(

I **think** if you run `pip show nislmigrate` to find where it's installed, edit `nislmigrate/migrators/repository_migrator.py` and change its name from `PackageRepository` to `Repository`, it will capture --repo data. No promises, and I unfortunately don't have time to run manual tests on an old version to validate my claims.

**Comment by ansible42** [comment]
Ok that appears to have got everything moved over, con the ```restore``` side I just renamed the ```Repository``` files back to ```PackageRepository``` and it seems to have gone through.  Though I am having other issues now.....
