### ISSUE TITLE
restore --secret  produces out of range error 

### ISSUE THREAD

**Issue by ansible42** [ni/NI-SystemLink-Migration#136]
![image](https://user-images.githubusercontent.com/5238787/141504868-bd0723be-fe30-44b4-afcc-a780e4429886.png)

Looks like an error in the argument parser.  

![image](https://user-images.githubusercontent.com/5238787/141505094-618611b4-7722-4f60-a330-214badeee4f0.png)

**Comment by Christian-Nunnally** [comment]
I was able to reproduce this with a test and fixed it in this PR: https://github.com/ni/NI-SystemLink-Migration/pull/137/files#diff-ca3d73959f0ab59fd110e957939a8c6393dd365befe92f55bb60c0814fa6a7a7. Will close this when that PR is submitted and a new release is created.

**Comment by ansible42** [comment]
thanks

**Comment by ansible42** [comment]
I manually updated to your latest and that appears to have done the trick.

**Comment by Christian-Nunnally** [comment]
The PR is merged now and 0.0.35 has the fix: https://github.com/ni/NI-SystemLink-Migration/releases/tag/0.0.35 

Thanks as always!
