### ISSUE TITLE
Secrete argument retuns an error 

### ISSUE THREAD

**Issue by ansible42** [ni/NI-SystemLink-Migration#145]
![image](https://user-images.githubusercontent.com/5238787/170730555-6716b35f-649e-4612-bdb9-72c360c42204.png)

Trying to use the secrete so that system states can be captured but it refuses to accept that as a valid argument.  Having run the ```--all``` option without the ```--secret``` none of the things that were require the password did not get captured

**Comment by Christian-Nunnally** [comment]
I think the issue might be that the `-v` argument can only go before the command argument, so `nislmigrate -v capture --all --secret password`

**Comment by ansible42** [comment]
![image](https://user-images.githubusercontent.com/5238787/170767088-7f8c7b8b-5eee-457a-b740-e104bc75cf9b.png)

**Comment by ansible42** [comment]
OK I uninstalled nislmigrate and reinstalled it in pip that appears to have fixed this issue.
